checks:
    php:
        code_rating: true
        duplication: true

filter:
    paths: [src/*]
    excluded_paths: [tests/*]

tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    external_code_coverage: true