language: php

php:
  - 7

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar self-update
  - php composer.phar install --dev --no-interaction

script:
  - mkdir -p build/logs
  - phpunit -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v
